# Variables
@baseUrl = http://localhost:3333


# Health Check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get Room
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create Room
# @name createRoom
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
    "name": "Sala De Teste",
    "description": "Essa é uma Sala de Teste"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get Room Questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create Question
# @name createQuestion
POST {{baseUrl}}/rooms/e7b2874d-f52c-4b14-9b2e-ee8ca30b83f6/questions
Accept: application/json
Content-Type: application/json

{
    "question": "What is React?"
}